name: PR Build

on:
  pull_request:

defaults:
  run:
    working-directory: ./app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - run: sh ./scripts/build.sh
        env:
          CI: true
      - name: Upload coverage
        uses: codecov/codecov-action@v1
