name: Unit Tests

on:
  pull_request:

defaults:
  working-directory: ./app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - run: npm install
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload coverage
        uses: codecov/codecov-action@v1
